### ISSUE TITLE
Getting Error: `Undefined index: expire_on_close`

### ISSUE THREAD

**Issue by mikebronner** [orchestral/testbench-dusk#15]
I'm getting the following error when trying to access routes in my package that have auth middleware:
```
[2018-02-11 01:40:20] testing.ERROR: Undefined index: expire_on_close {"exception":"[object] (ErrorException(code: 0): Undefined index: expire_on_close at /Users/mike/Developer/Sites/laravel-governor/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:203)
[stacktrace]
#0 /Users/mike/Developer/Sites/laravel-governor/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(203): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined index...', '/Users/mike/Dev...', 203, Array)
#1 /Users/mike/Developer/Sites/laravel-governor/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(177): Illuminate\\Session\\Middleware\\StartSession->getCookieExpirationDate()
#2 /Users/mike/Developer/Sites/laravel-governor/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(71): Illuminate\\Session\\Middleware\\StartSession->addCookieToResponse(Object(Illuminate\\Http\\RedirectResponse), Object(Illuminate\\Session\\Store))
#3 /Users/mike/Developer/Sites/laravel-governor/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#4 /Users/mike/Developer/Sites/laravel-governor/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#5 /Users/mike/Developer/Sites/laravel-governor/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#6 /Users/mike/Developer/Sites/laravel-governor/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#7 /Users/mike/Developer/Sites/laravel-governor/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#8 /Users/mike/Developer/Sites/laravel-governor/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#9 /Users/mike/Developer/Sites/laravel-governor/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#10 /Users/mike/Developer/Sites/laravel-governor/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#11 /Users/mike/Developer/Sites/laravel-governor/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#12 /Users/mike/Developer/Sites/laravel-governor/vendor/laravel/framework/src/Illuminate/Routing/Router.php(661): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#13 /Users/mike/Developer/Sites/laravel-governor/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#14 /Users/mike/Developer/Sites/laravel-governor/vendor/laravel/framework/src/Illuminate/Routing/Router.php(602): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#15 /Users/mike/Developer/Sites/laravel-governor/vendor/laravel/framework/src/Illuminate/Routing/Router.php(591): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#16 /Users/mike/Developer/Sites/laravel-governor/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#17 /Users/mike/Developer/Sites/laravel-governor/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#18 /Users/mike/Developer/Sites/laravel-governor/vendor/genealabs/laravel-casts/src/Http/Middleware/AssetInjection.php(10): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 /Users/mike/Developer/Sites/laravel-governor/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): GeneaLabs\\LaravelCasts\\Http\\Middleware\\AssetInjection->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /Users/mike/Developer/Sites/laravel-governor/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /Users/mike/Developer/Sites/laravel-governor/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /Users/mike/Developer/Sites/laravel-governor/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /Users/mike/Developer/Sites/laravel-governor/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /Users/mike/Developer/Sites/laravel-governor/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#25 /Users/mike/Developer/Sites/laravel-governor/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /Users/mike/Developer/Sites/laravel-governor/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /Users/mike/Developer/Sites/laravel-governor/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 /Users/mike/Developer/Sites/laravel-governor/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /Users/mike/Developer/Sites/laravel-governor/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /Users/mike/Developer/Sites/laravel-governor/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 /Users/mike/Developer/Sites/laravel-governor/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#32 /Users/mike/Developer/Sites/laravel-governor/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#33 /Users/mike/Developer/Sites/laravel-governor/vendor/orchestra/testbench-dusk/src/server.php(44): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#34 {main}
"} 
```

It's probably something I'm missing or doing wrong on my end, but I have no idea why this would be.

Here's my test:
```php
    public function testAuthenticatedUserCanSeeInitialRoles()
    {
        $user = (new User)->create([
            'name' => 'Joe Test',
            'email' => 'none@noemail.com',
            'password' => 'not hashed but who cares',
        ]);

        $this->browse(function ($browser) use ($user) {
            $response = $browser->loginAs($user)
                ->visit(route('genealabs.laravel-governor.assignments.index'));
            $response->dump();
            $response->assertSee('Member');
            $response->assertSee('SuperAdmin');
            $response->closeAll();
        });
    }
```

Here's my CreatesApplication.php:
```php
<?php namespace GeneaLabs\LaravelGovernor\Tests;

use GeneaLabs\LaravelGovernor\Providers\Service as LaravelGovernorService;
use GeneaLabs\LaravelGovernor\Tests\Models\User;
use Orchestra\Database\ConsoleServiceProvider;
use Illuminate\Support\Facades\Auth;

trait CreatesApplication
{
    public function setUp()
    {
        parent::setUp();

        $this->withFactories(__DIR__ . '/database/factories');
        $this->loadMigrationsFrom(__DIR__ . '/database/migrations');
        $this->loadMigrationsFrom(__DIR__ . '../database/migrations');

        config(['genealabs-laravel-governor.auth-model' => User::class]);
    }

    /**
     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
     */
    protected function getPackageProviders($app)
    {
        Auth::routes();
        return [
            LaravelGovernorService::class,
            ConsoleServiceProvider::class,
        ];
    }
}
```

From a bit of initial investigation, it would appear that the StartSession middleware is called before the config settings are loaded? The data contained in the session config is:
```php
[
  "driver" => "file"
  "lifetime" => 120
  "encrypt" => false
  "files" => "/Users/mike/Developer/Sites/laravel-governor/vendor/orchestra/testbench-dusk/src/../laravel/storage/framework/sessions"
  "connection" => null
  "table" => "sessions"
  "store" => null
  "lottery" => [...]
  "cookie" => "laravel_session"
  "path" => "/"
  "domain" => null
  "secure" => false
  "http_only" => true
  "same_site" => null
]
```

This, despite me specifying that it should set that setting in CreatesApplication (see above). It seems that the app running inside the dusk browser is not correctly loading session config file, or perhaps is being overwritten somewhere else? (Looking at `getSessionConfig()` in SessionManager would indicate that the incorrect settings are loaded into the application.)

If you have any thoughts what I might be doing wrong, that would be great. Thanks for your help! :)

**Comment by crynobone** [comment]
This should be fixed on the upcoming patch release.
